### Not work
GET http://localhost:1323

### Index - User List
GET http://localhost:1323/users
content-type: application/json

{
    "id": 0
}

### Index - User Info of id #1
GET http://localhost:1323/users
content-type: application/json

{
    "id": 1
}

### Create - FormValue로 불러올 경우 / 안 씀
# POST http://localhost:1323/users
# Content-Type: application/x-www-form-urlencoded

# username=mast&password=123&email=haha@haha.com

### Create
POST http://localhost:1323/users
content-type: application/json

{
    "username" : "mast",
    "email" : "liverty@liberty.union",
    "password" : "123"
}

### Update
PUT http://localhost:1323/users
content-type: application/json

{
    "id" : 1,
    "username" : "master",
    "email" : "master@nation.gov",
    "password" : "12345"
}

### Update
PUT http://localhost:1323/users
content-type: application/json

{
    "id" : 37,
    "username" : "mastery",
    "email" : "master@middle.earth",
    "password" : "123456"
}

### Delete - token not yet work
DELETE http://localhost:1323/users
content-type: application/json

{
    "id" : 4
}

### JWT - Login
POST http://localhost:1323/login
content-type: application/json

{
    "username" : "master",
    "password" : "12345"
}

### JWT - Login
POST http://localhost:1323/login
content-type: application/json

{
    "username" : "mastery",
    "password" : "123456"
}

### JWT - Restricted contents
GET http://localhost:1323/restricted
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWFzdGVyIiwiYWRtaW4iOnRydWUsImV4cCI6MTU1MDgzMjE2OH0.6M-tKTUiPgtM0wVVJQqu8kZh0r1E7jeWBNVCMBDdsaQ
